### ISSUE TITLE
LGPL3 License

### ISSUE THREAD

**Issue by malkia** [woboq/verdigris#22]
First, this is a great project, and I would love if we could've used it, but this licensing stops us, as we may release an app (used only internally so far) outside at some point, but using this would force us to release all source code that uses it.

Then again, I understand choices, and I do not dispute that. I'm simply asking if there would be chance for engineers in my position to gain a lot from it.

At this point, even having commercial license might be better for us! (Granted that we do a trial, change our code to use it, and compare the savings - we mainly looking to reduce build time, as .moc generation tend to not work well with SN-DBS).

**Comment by smokku** [comment]
https://linux.slashdot.org/story/11/03/20/1529238/rms-on-header-files-and-derivative-works

> Our view is that just using structure definitions, typedefs, enumeration constants, macros with simple bodies, etc., is NOT enough to make a derivative work. It would take a substantial amount of code (coming from inline functions or macros with substantial bodies) to do that.'

**Comment by jcelerier** [comment]
> using this would force us to release all source code that uses it.

if LGPL worked like this you couldn't use Qt under LGPL at all since for instance QVector, QList, etc... are under LGPL and header-only.

**Comment by jcelerier** [comment]
Here is the LGPL legalese on this : 
   

> 3. Object Code Incorporating  Material from Library Header Files.
> 
> **The object code form of an Application may incorporate material from a header file that is part of the Library. You may convey such object code under terms of your choice**, provided that, if the incorporated material is not limited to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), you do both of the following:
> 
>     a) Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License.
>     b) Accompany the object code with a copy of the GNU GPL and this license document.
>

**Comment by ogoffart** [comment]
@malkia please contact us by email, and we will be happy to negociate a commercial license that suits your needs.

As stated in the README, the license is chosen to be compatible with the Qt license.
And you only need to publish the code of this library and its modifications, as well as stating that you use the library.
Since it is header-only, the part that say that the user need to be able to change the library underneath does not apply (as per the exceptions already quoted in previous comments)

(The question is wether the code comming from the macro and inline functions is substential. But it is mostly meta-programmation. What ends up in the binary is limited to the QMetaObject data.)
