### ISSUE TITLE
Version 1.3

### ISSUE THREAD

**Issue by ShalokShalom** [woboq/verdigris#92]
Considering the significant amount of contributions since 1.2, that happened in 2019, I suggest a new version to be released here.

And considering that there are already two other issues who raise awareness about missing released, I also suggest a frequent release schedule.

Does anyone love to sign up for this?

**Comment by arBmind** [comment]
@ShalokShalom You are not wrong. But this project lost a bit of structure and vision since @ogoffart is focusing on other projects.

I got a bit carried away because I needed to optimize compile time as much as possible. So my branch is now C++20 and Qt 6.2.4+ only. But I have fixed some issues with Qt6.3+ and also full W_BINDABLE support.

One way would be to make a 1.3 release with the old prerequisites Qt 5+ and C++14.
And add a 2.0 branch with C++20 and Qt 6.2.4+ to move on?
Frequent releases are difficult because this project has no funding, so we rely on spare time participants.

My major concern right now is that, we have no good approach for QML_ELEMENT. (See #83)
Without that I see no long term future for Verdigris. Unfortunately right now nobody seems to be willing to fund this risky development.

But let me know if my release strategy is worth the effort.

**Comment by jcelerier** [comment]
> And add a 2.0 branch with C++20 and Qt 6.2.4+ to move on?

makes a lot of sense to me! I don't think there's a lot of people who would simultaneously 
- Use the latest version of verdigris
- Use the latest version of Qt
- Use an older compiler which does not support C++20 - I don't think it's even meaningfully possible as from what I see from the compiler requirements of Qt 6 (GCC 9, Clang 11), all these compilers already support c++20's language features to a large extent (except modules)

> My major concern right now is that, we have no good approach for QML_ELEMENT.

I don't really use QML anymore, can't help with this sorry :/

**Comment by ShalokShalom** [comment]
> One way would be to make a 1.3 release with the old prerequisites Qt 5+ and C++14.
> And add a 2.0 branch with C++20 and Qt 6.2.4+ to move on?

Sounds awesome

**Comment by ogoffart** [comment]
A 1.3 release at this point makes total sense, thanks to all the contributors

**Comment by ShalokShalom** [comment]
Wonderful ❤️
